package defpackage;

/* loaded from: classes.dex */
public interface kb0 {
    public static final s A;
    public static final s B;
    public static final s C;
    public static final s D;
    public static final s E;
    public static final s F;
    public static final s G;
    public static final s H;
    public static final s I;
    public static final s J;
    public static final s K;
    public static final s L;
    public static final s M;
    public static final s N;
    public static final s O;
    public static final s P;
    public static final s Q;
    public static final s R;
    public static final s S;
    public static final s T;
    public static final s a;
    public static final s b;
    public static final s c;
    public static final s d;
    public static final s e;
    public static final s f;
    public static final s g;
    public static final s h;
    public static final s i;
    public static final s j;
    public static final s k;
    public static final s l;
    public static final s m;
    public static final s n;
    public static final s o;
    public static final s p;
    public static final s q;
    public static final s r;
    public static final s s;
    public static final s t;
    public static final s u;
    public static final s v;
    public static final s w;
    public static final s x;
    public static final s y;
    public static final s z;

    static {
        s sVar = new s("2.16.840.1.101.3.4");
        s q2 = sVar.q("2");
        a = q2.q("1");
        b = q2.q("2");
        c = q2.q("3");
        d = q2.q("4");
        q2.q("5");
        e = q2.q("6");
        q2.q("7");
        f = q2.q("8");
        q2.q("9");
        q2.q("10");
        g = q2.q("11");
        h = q2.q("12");
        qo0.w(q2, "13", "14", "15", "16");
        q2.q("17");
        i = q2.q("18");
        qo0.w(q2, "19", "20", "21", "22");
        s q3 = sVar.q("1");
        q3.q("1");
        q3.q("2");
        q3.q("3");
        qo0.w(q3, "4", "5", "6", "7");
        qo0.w(q3, "8", "9", "21", "22");
        qo0.w(q3, "23", "24", "25", "26");
        qo0.w(q3, "27", "28", "29", "41");
        qo0.w(q3, "42", "43", "44", "45");
        qo0.w(q3, "46", "47", "48", "49");
        s q4 = sVar.q("3");
        j = q4.q("1");
        k = q4.q("2");
        l = q4.q("3");
        m = q4.q("4");
        qo0.w(q4, "5", "6", "7", "8");
        qo0.w(q4, "9", "10", "11", "12");
        qo0.w(q4, "13", "14", "15", "16");
        n = q4.q("17");
        o = q4.q("18");
        p = q4.q("19");
        q = q4.q("32");
        r = q4.q("33");
        s = q4.q("34");
        t = q4.q("20");
        u = q4.q("21");
        v = q4.q("22");
        w = q4.q("23");
        x = q4.q("24");
        y = q4.q("25");
        z = q4.q("26");
        A = q4.q("27");
        B = q4.q("28");
        C = q4.q("29");
        D = q4.q("30");
        E = q4.q("31");
        F = q4.q("35");
        G = q4.q("36");
        H = q4.q("37");
        I = q4.q("38");
        J = q4.q("39");
        K = q4.q("40");
        L = q4.q("41");
        M = q4.q("42");
        N = q4.q("43");
        O = q4.q("44");
        P = q4.q("45");
        Q = q4.q("46");
        s q5 = sVar.q("4");
        R = q5.q("1");
        S = q5.q("2");
        T = q5.q("3");
    }
}
