package defpackage;

import android.R;

/* loaded from: classes.dex */
public abstract class kg0 {
    public static final int[] a = {R.attr.selectableItemBackground, svarzee.android.apps.adb_mouse.R.attr.selectableItemBackground};
    public static final int[] b = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, svarzee.android.apps.adb_mouse.R.attr.disableDependentsState, svarzee.android.apps.adb_mouse.R.attr.summaryOff, svarzee.android.apps.adb_mouse.R.attr.summaryOn};
    public static final int[] c = {R.attr.dialogTitle, R.attr.dialogMessage, R.attr.dialogIcon, R.attr.positiveButtonText, R.attr.negativeButtonText, R.attr.dialogLayout, svarzee.android.apps.adb_mouse.R.attr.dialogIcon, svarzee.android.apps.adb_mouse.R.attr.dialogLayout, svarzee.android.apps.adb_mouse.R.attr.dialogMessage, svarzee.android.apps.adb_mouse.R.attr.dialogTitle, svarzee.android.apps.adb_mouse.R.attr.negativeButtonText, svarzee.android.apps.adb_mouse.R.attr.positiveButtonText};
    public static final int[] d = {svarzee.android.apps.adb_mouse.R.attr.useSimpleSummaryProvider};
    public static final int[] e = {R.attr.entries, R.attr.entryValues, svarzee.android.apps.adb_mouse.R.attr.entries, svarzee.android.apps.adb_mouse.R.attr.entryValues, svarzee.android.apps.adb_mouse.R.attr.useSimpleSummaryProvider};
    public static final int[] f = {R.attr.entries, R.attr.entryValues, svarzee.android.apps.adb_mouse.R.attr.entries, svarzee.android.apps.adb_mouse.R.attr.entryValues};
    public static final int[] g = {R.attr.icon, R.attr.persistent, R.attr.enabled, R.attr.layout, R.attr.title, R.attr.selectable, R.attr.key, R.attr.summary, R.attr.order, R.attr.widgetLayout, R.attr.dependency, R.attr.defaultValue, R.attr.shouldDisableView, R.attr.fragment, R.attr.singleLineTitle, R.attr.iconSpaceReserved, svarzee.android.apps.adb_mouse.R.attr.allowDividerAbove, svarzee.android.apps.adb_mouse.R.attr.allowDividerBelow, svarzee.android.apps.adb_mouse.R.attr.defaultValue, svarzee.android.apps.adb_mouse.R.attr.dependency, svarzee.android.apps.adb_mouse.R.attr.enableCopying, svarzee.android.apps.adb_mouse.R.attr.enabled, svarzee.android.apps.adb_mouse.R.attr.fragment, svarzee.android.apps.adb_mouse.R.attr.icon, svarzee.android.apps.adb_mouse.R.attr.iconSpaceReserved, svarzee.android.apps.adb_mouse.R.attr.isPreferenceVisible, svarzee.android.apps.adb_mouse.R.attr.key, svarzee.android.apps.adb_mouse.R.attr.layout, svarzee.android.apps.adb_mouse.R.attr.order, svarzee.android.apps.adb_mouse.R.attr.persistent, svarzee.android.apps.adb_mouse.R.attr.selectable, svarzee.android.apps.adb_mouse.R.attr.shouldDisableView, svarzee.android.apps.adb_mouse.R.attr.singleLineTitle, svarzee.android.apps.adb_mouse.R.attr.summary, svarzee.android.apps.adb_mouse.R.attr.title, svarzee.android.apps.adb_mouse.R.attr.widgetLayout};
    public static final int[] h = {R.attr.layout, R.attr.divider, R.attr.dividerHeight, svarzee.android.apps.adb_mouse.R.attr.allowDividerAfterLastItem};
    public static final int[] i = {R.attr.orderingFromXml, svarzee.android.apps.adb_mouse.R.attr.initialExpandedChildrenCount, svarzee.android.apps.adb_mouse.R.attr.orderingFromXml};
    public static final int[] j = {R.attr.maxWidth, R.attr.maxHeight, svarzee.android.apps.adb_mouse.R.attr.maxHeight, svarzee.android.apps.adb_mouse.R.attr.maxWidth};
    public static final int[] k = {R.attr.layout, R.attr.max, svarzee.android.apps.adb_mouse.R.attr.adjustable, svarzee.android.apps.adb_mouse.R.attr.min, svarzee.android.apps.adb_mouse.R.attr.seekBarIncrement, svarzee.android.apps.adb_mouse.R.attr.showSeekBarValue, svarzee.android.apps.adb_mouse.R.attr.updatesContinuously};
    public static final int[] l = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, svarzee.android.apps.adb_mouse.R.attr.disableDependentsState, svarzee.android.apps.adb_mouse.R.attr.summaryOff, svarzee.android.apps.adb_mouse.R.attr.summaryOn, svarzee.android.apps.adb_mouse.R.attr.switchTextOff, svarzee.android.apps.adb_mouse.R.attr.switchTextOn};
    public static final int[] m = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, svarzee.android.apps.adb_mouse.R.attr.disableDependentsState, svarzee.android.apps.adb_mouse.R.attr.summaryOff, svarzee.android.apps.adb_mouse.R.attr.summaryOn, svarzee.android.apps.adb_mouse.R.attr.switchTextOff, svarzee.android.apps.adb_mouse.R.attr.switchTextOn};
}
