package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* compiled from: r8-map-id-a449a41cc305adace0fb5eba15534f9e326e1bcd513b1eb0f49c7e6b20d3b31a */
/* loaded from: classes.dex */
public final class uj {
    public int a;
    public final xj b;
    public final wj c;
    public final vj d;
    public final yj e;
    public HashMap f;

    /* JADX WARN: Type inference failed for: r0v0, types: [xj, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v1, types: [wj, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v2, types: [vj, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v3, types: [yj, java.lang.Object] */
    public uj() {
        ?? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ?? obj2 = new Object();
        obj2.a = -1;
        obj2.b = 0;
        obj2.c = -1;
        obj2.d = Float.NaN;
        obj2.e = Float.NaN;
        obj2.f = Float.NaN;
        obj2.g = -1;
        obj2.h = null;
        obj2.i = -1;
        this.c = obj2;
        ?? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = true;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = -1;
        obj3.w = 0.5f;
        obj3.x = 0.5f;
        obj3.y = null;
        obj3.z = -1;
        obj3.A = 0;
        obj3.B = 0.0f;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = 0;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = 0;
        obj3.M = Integer.MIN_VALUE;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = Integer.MIN_VALUE;
        obj3.T = -1.0f;
        obj3.U = -1.0f;
        obj3.V = 0;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = 0;
        obj3.Z = 0;
        obj3.a0 = 0;
        obj3.b0 = 0;
        obj3.c0 = 0;
        obj3.d0 = 1.0f;
        obj3.e0 = 1.0f;
        obj3.f0 = -1;
        obj3.g0 = 0;
        obj3.h0 = -1;
        obj3.l0 = false;
        obj3.m0 = false;
        obj3.n0 = true;
        obj3.o0 = 0;
        this.d = obj3;
        ?? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = -1;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = 0.0f;
        obj4.l = false;
        obj4.m = 0.0f;
        this.e = obj4;
        this.f = new HashMap();
    }

    public final void a(qj qjVar) {
        vj vjVar = this.d;
        qjVar.e = vjVar.h;
        qjVar.f = vjVar.i;
        qjVar.g = vjVar.j;
        qjVar.h = vjVar.k;
        qjVar.i = vjVar.l;
        qjVar.j = vjVar.m;
        qjVar.k = vjVar.n;
        qjVar.l = vjVar.o;
        qjVar.m = vjVar.p;
        qjVar.n = vjVar.q;
        qjVar.o = vjVar.r;
        qjVar.s = vjVar.s;
        qjVar.t = vjVar.t;
        qjVar.u = vjVar.u;
        qjVar.v = vjVar.v;
        ((ViewGroup.MarginLayoutParams) qjVar).leftMargin = vjVar.F;
        ((ViewGroup.MarginLayoutParams) qjVar).rightMargin = vjVar.G;
        ((ViewGroup.MarginLayoutParams) qjVar).topMargin = vjVar.H;
        ((ViewGroup.MarginLayoutParams) qjVar).bottomMargin = vjVar.I;
        qjVar.A = vjVar.R;
        qjVar.B = vjVar.Q;
        qjVar.x = vjVar.N;
        qjVar.z = vjVar.P;
        qjVar.E = vjVar.w;
        qjVar.F = vjVar.x;
        qjVar.p = vjVar.z;
        qjVar.q = vjVar.A;
        qjVar.r = vjVar.B;
        qjVar.G = vjVar.y;
        qjVar.T = vjVar.C;
        qjVar.U = vjVar.D;
        qjVar.I = vjVar.T;
        qjVar.H = vjVar.U;
        qjVar.K = vjVar.W;
        qjVar.J = vjVar.V;
        qjVar.W = vjVar.l0;
        qjVar.X = vjVar.m0;
        qjVar.L = vjVar.X;
        qjVar.M = vjVar.Y;
        qjVar.P = vjVar.Z;
        qjVar.Q = vjVar.a0;
        qjVar.N = vjVar.b0;
        qjVar.O = vjVar.c0;
        qjVar.R = vjVar.d0;
        qjVar.S = vjVar.e0;
        qjVar.V = vjVar.E;
        qjVar.c = vjVar.f;
        qjVar.a = vjVar.d;
        qjVar.b = vjVar.e;
        ((ViewGroup.MarginLayoutParams) qjVar).width = vjVar.b;
        ((ViewGroup.MarginLayoutParams) qjVar).height = vjVar.c;
        String str = vjVar.k0;
        if (str != null) {
            qjVar.Y = str;
        }
        qjVar.Z = vjVar.o0;
        qjVar.setMarginStart(vjVar.K);
        qjVar.setMarginEnd(vjVar.J);
        qjVar.a();
    }

    public final Object clone() {
        uj ujVar = new uj();
        vj vjVar = ujVar.d;
        vjVar.getClass();
        vj vjVar2 = this.d;
        vjVar.a = vjVar2.a;
        vjVar.b = vjVar2.b;
        vjVar.c = vjVar2.c;
        vjVar.d = vjVar2.d;
        vjVar.e = vjVar2.e;
        vjVar.f = vjVar2.f;
        vjVar.g = vjVar2.g;
        vjVar.h = vjVar2.h;
        vjVar.i = vjVar2.i;
        vjVar.j = vjVar2.j;
        vjVar.k = vjVar2.k;
        vjVar.l = vjVar2.l;
        vjVar.m = vjVar2.m;
        vjVar.n = vjVar2.n;
        vjVar.o = vjVar2.o;
        vjVar.p = vjVar2.p;
        vjVar.q = vjVar2.q;
        vjVar.r = vjVar2.r;
        vjVar.s = vjVar2.s;
        vjVar.t = vjVar2.t;
        vjVar.u = vjVar2.u;
        vjVar.v = vjVar2.v;
        vjVar.w = vjVar2.w;
        vjVar.x = vjVar2.x;
        vjVar.y = vjVar2.y;
        vjVar.z = vjVar2.z;
        vjVar.A = vjVar2.A;
        vjVar.B = vjVar2.B;
        vjVar.C = vjVar2.C;
        vjVar.D = vjVar2.D;
        vjVar.E = vjVar2.E;
        vjVar.F = vjVar2.F;
        vjVar.G = vjVar2.G;
        vjVar.H = vjVar2.H;
        vjVar.I = vjVar2.I;
        vjVar.J = vjVar2.J;
        vjVar.K = vjVar2.K;
        vjVar.L = vjVar2.L;
        vjVar.M = vjVar2.M;
        vjVar.N = vjVar2.N;
        vjVar.O = vjVar2.O;
        vjVar.P = vjVar2.P;
        vjVar.Q = vjVar2.Q;
        vjVar.R = vjVar2.R;
        vjVar.S = vjVar2.S;
        vjVar.T = vjVar2.T;
        vjVar.U = vjVar2.U;
        vjVar.V = vjVar2.V;
        vjVar.W = vjVar2.W;
        vjVar.X = vjVar2.X;
        vjVar.Y = vjVar2.Y;
        vjVar.Z = vjVar2.Z;
        vjVar.a0 = vjVar2.a0;
        vjVar.b0 = vjVar2.b0;
        vjVar.c0 = vjVar2.c0;
        vjVar.d0 = vjVar2.d0;
        vjVar.e0 = vjVar2.e0;
        vjVar.f0 = vjVar2.f0;
        vjVar.g0 = vjVar2.g0;
        vjVar.h0 = vjVar2.h0;
        vjVar.k0 = vjVar2.k0;
        int[] iArr = vjVar2.i0;
        if (iArr != null && vjVar2.j0 == null) {
            vjVar.i0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            vjVar.i0 = null;
        }
        vjVar.j0 = vjVar2.j0;
        vjVar.l0 = vjVar2.l0;
        vjVar.m0 = vjVar2.m0;
        vjVar.n0 = vjVar2.n0;
        vjVar.o0 = vjVar2.o0;
        wj wjVar = ujVar.c;
        wjVar.getClass();
        wj wjVar2 = this.c;
        wjVar2.getClass();
        wjVar.a = wjVar2.a;
        wjVar.c = wjVar2.c;
        wjVar.e = wjVar2.e;
        wjVar.d = wjVar2.d;
        xj xjVar = this.b;
        int i = xjVar.a;
        xj xjVar2 = ujVar.b;
        xjVar2.a = i;
        xjVar2.c = xjVar.c;
        xjVar2.d = xjVar.d;
        xjVar2.b = xjVar.b;
        yj yjVar = ujVar.e;
        yjVar.getClass();
        yj yjVar2 = this.e;
        yjVar2.getClass();
        yjVar.a = yjVar2.a;
        yjVar.b = yjVar2.b;
        yjVar.c = yjVar2.c;
        yjVar.d = yjVar2.d;
        yjVar.e = yjVar2.e;
        yjVar.f = yjVar2.f;
        yjVar.g = yjVar2.g;
        yjVar.h = yjVar2.h;
        yjVar.i = yjVar2.i;
        yjVar.j = yjVar2.j;
        yjVar.k = yjVar2.k;
        yjVar.l = yjVar2.l;
        yjVar.m = yjVar2.m;
        ujVar.a = this.a;
        return ujVar;
    }
}
