package defpackage;

/* compiled from: r8-map-id-a449a41cc305adace0fb5eba15534f9e326e1bcd513b1eb0f49c7e6b20d3b31a */
/* loaded from: classes.dex */
public abstract class v61 {
    public static final td a;
    public static final td b;
    public static final td c;
    public static final td d;
    public static final td e;
    public static final td f;
    public static final td g;
    public static final td h;
    public static final td i;
    public static final td j;
    public static final td k;
    public static final td l;
    public static final td m;
    public static final td n;
    public static final td o;
    public static final td p;

    static {
        sd a2 = td.a();
        a2.b = 3;
        a2.d = "Google Play In-app Billing API version is less than 3";
        a2.a();
        sd a3 = td.a();
        a3.b = 3;
        a3.d = "Google Play In-app Billing API version is less than 9";
        a3.a();
        sd a4 = td.a();
        a4.b = 3;
        a4.d = "Billing service unavailable on device.";
        a = a4.a();
        sd a5 = td.a();
        a5.b = 2;
        a5.d = "Billing service unavailable on device.";
        b = a5.a();
        sd a6 = td.a();
        a6.b = 5;
        a6.d = "Client is already in the process of connecting to billing service.";
        c = a6.a();
        sd a7 = td.a();
        a7.b = 5;
        a7.d = "The list of SKUs can't be empty.";
        a7.a();
        sd a8 = td.a();
        a8.b = 5;
        a8.d = "SKU type can't be empty.";
        a8.a();
        sd a9 = td.a();
        a9.b = 5;
        a9.d = "Product type can't be empty.";
        d = a9.a();
        sd a10 = td.a();
        a10.b = -2;
        a10.d = "Client does not support extra params.";
        e = a10.a();
        sd a11 = td.a();
        a11.b = 5;
        a11.d = "Invalid purchase token.";
        a11.a();
        sd a12 = td.a();
        a12.b = 6;
        a12.d = "An internal error occurred.";
        f = a12.a();
        sd a13 = td.a();
        a13.b = 5;
        a13.d = "SKU can't be null.";
        a13.a();
        sd a14 = td.a();
        a14.b = 0;
        g = a14.a();
        sd a15 = td.a();
        a15.b = -1;
        a15.d = "Service connection is disconnected.";
        h = a15.a();
        sd a16 = td.a();
        a16.b = 2;
        a16.d = "Timeout communicating with service.";
        i = a16.a();
        sd a17 = td.a();
        a17.b = -2;
        a17.d = "Client does not support subscriptions.";
        j = a17.a();
        sd a18 = td.a();
        a18.b = -2;
        a18.d = "Client does not support subscriptions update.";
        a18.a();
        sd a19 = td.a();
        a19.b = -2;
        a19.d = "Client does not support get purchase history.";
        a19.a();
        sd a20 = td.a();
        a20.b = -2;
        a20.d = "Client does not support price change confirmation.";
        a20.a();
        sd a21 = td.a();
        a21.b = -2;
        a21.d = "Play Store version installed does not support cross selling products.";
        a21.a();
        sd a22 = td.a();
        a22.b = -2;
        a22.d = "Client does not support multi-item purchases.";
        k = a22.a();
        sd a23 = td.a();
        a23.b = -2;
        a23.d = "Client does not support offer_id_token.";
        l = a23.a();
        sd a24 = td.a();
        a24.b = -2;
        a24.d = "Client does not support ProductDetails.";
        m = a24.a();
        sd a25 = td.a();
        a25.b = -2;
        a25.d = "Client does not support in-app messages.";
        a25.a();
        sd a26 = td.a();
        a26.b = -2;
        a26.d = "Client does not support user choice billing.";
        a26.a();
        sd a27 = td.a();
        a27.b = -2;
        a27.d = "Play Store version installed does not support external offer.";
        a27.a();
        sd a28 = td.a();
        a28.b = -2;
        a28.d = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a28.a();
        sd a29 = td.a();
        a29.b = -2;
        a29.d = "Play Store version installed does not support querying AutoPay plan purchase.";
        a29.a();
        sd a30 = td.a();
        a30.b = -2;
        a30.d = "Play Store version installed does not support including suspended subscriptions.";
        a30.a();
        sd a31 = td.a();
        a31.b = 5;
        a31.d = "Unknown feature";
        a31.a();
        sd a32 = td.a();
        a32.b = -2;
        a32.d = "Play Store version installed does not support get billing config.";
        a32.a();
        sd a33 = td.a();
        a33.b = -2;
        a33.d = "Query product details with serialized docid is not supported.";
        a33.a();
        sd a34 = td.a();
        a34.b = -2;
        a34.d = "Play Store version installed does not support launching external offer flow.";
        a34.a();
        sd a35 = td.a();
        a35.b = 4;
        a35.d = "Item is unavailable for purchase.";
        n = a35.a();
        sd a36 = td.a();
        a36.b = -2;
        a36.d = "Query product details with developer specified account is not supported.";
        a36.a();
        sd a37 = td.a();
        a37.b = -2;
        a37.d = "Play Store version installed does not support alternative billing only.";
        a37.a();
        sd a38 = td.a();
        a38.b = 5;
        a38.d = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        o = a38.a();
        sd a39 = td.a();
        a39.b = 6;
        a39.d = "An error occurred while retrieving billing override.";
        p = a39.a();
        sd a40 = td.a();
        a40.b = -2;
        a40.d = "Play Store version installed does not support the provided billing program.";
        a40.a();
        sd a41 = td.a();
        a41.b = -2;
        a41.d = "Play Store version installed does not support launching external links.";
        a41.a();
        sd a42 = td.a();
        a42.b = 5;
        a42.d = "A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.";
        a42.a();
    }

    public static td a(String str, int i2) {
        sd a2 = td.a();
        a2.b = i2;
        a2.d = str;
        return a2.a();
    }
}
